version: 2.1
jobs:
    build:
        working_directory: ~/tmp
        docker:
            - image: circleci/node:11
        steps:
            - checkout
            - run: npm install
            - run: npm test
