version: 2.1
jobs:
    build:
        working_directory: ~/repo

        docker:
            - image: circleci/node:10
            - image: circleci/postgres:9.6.2-alpine
              environment:
                  POSTGRES_USER: root
                  POSTGRES_PASSWORD: root
                  POSTGRES_DB: cloud

        steps:
            - checkout
            - run: cd vue && npm install
            - run: cd vue && npm run build
            # - run: cd vue && npm run start
            # - run: npm test
