version: 2.1
jobs:
    build:
        working_directory: ~/repo

        docker:
            - image: circleci/node:10

        steps:
            - checkout
            - run: npm install
            # - run: npm test
