version: 2.1
jobs:
    build:
        working_directory: ~/repo

        docker:
            - image: circleci/node:10

        steps:
            - checkout
            - run: cd vue && npm install
            - run: cd vue && npm run build
            # - run: cd vue && npm run start
            # - run: npm test
