version: 2.1
jobs:
    build:
        working_directory: ~/repo

        docker:
            environment:
                DOCKER_HOST: vue

            - image: circleci/node:10
              environment:
                  PGHOST: 127.0.0.1
                  PGUSER: root

            - image: circleci/postgres:11.1-alpine-ram
              environment:
                  POSTGRES_USER: root
                  POSTGRES_PASSWORD: root
                  POSTGRES_DB: root

        steps:
            - checkout

            - run:
                  name: Updating linux
                  command: sudo apt-get update

            - run:
                  name: Installing postgresql
                  command: sudo apt-get install postgresql

            - run:
                  name: Importing database
                  command: psql < vue/setup.sql

            - run:
                  name: Setting up config files
                  command: cd vue/config &&
                      cp db.config-default.json db.config.json &&
                      cp jwt.config-default.json jwt.config.json &&
                      cp mail.config-default.json mail.config.json &&
                      cp svgo.config-default.json svgo.config.json

            - restore_cache:
                  keys:
                      - dependency-cache-{{ .Branch }}-{{ checksum "vue/package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - dependency-cache-{{ .Branch }}-

            - run:
                  name: Docker compose
                  command: |
                      cd vue
                      set -x
                      docker-compose up --build -d

            # - run:
            #       name: Installing NPM packages
            #       command: cd vue && npm i

            # - run:
            #       name: Installing peer NPM packages
            #       command: cd vue && npm i @vue/cli-plugin-e2e-cypress @vue/cli-plugin-eslint

            # - run:
            #       name: Linting code
            #       command: cd vue && npm run lint

            # - run:
            #       name: Building server
            #       command: cd vue && npm run build

            - save_cache:
                  key: dependency-cache-{{ .Branch }}-{{ checksum "vue/package.json" }}
                  paths:
                      - node_modules

            # - run:
            #       name: Installing cypress dependencies
            #       command: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

            # - run:
            #       name: Running cypress
            #       command: cd vue && npm run test:headless

            - store_artifacts:
                  path: vue/tests/e2e/videos

            - store_artifacts:
                  path: vue/tests/e2e/screenshots
