version: '3'

volumes:
    app-dist: {}

services:
    app:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - app-dist:/home/node/exomia-cloud/dist
            - ./config/:/home/node/exomia-cloud/config/:ro

    nginx:
        image: nginx:1.15-alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - app-dist:/var/www/html
