version: '3'

volumes:
    app-dist: {}

services:
    app:
        build: .
        volumes:
            - app-dist:/home/node/app/dist

    nginx:
        image: nginx:1.15-alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - app-dist:/var/www/html
